In [1]:
import torch

1) What is a tensor (really)?

A tensor is just a multi-dimensional array (numbers arranged in 0D, 1D, 2D, 3D, …).

0D: scalar (e.g., 3.14)

1D: vector (e.g., [1,2,3])

2D: matrix (rows × columns)

3D+: stacks of matrices (for images: N × C × H × W, etc.)

PyTorch tensors:

live on CPU or GPU

know their dtype (float32, int64, …)

track shape (torch.Size([..]))

can participate in fast, vectorized math

## 2. The essentials you’ll use every day
Create tensors

In [2]:
# from Python data
x = torch.tensor([1.0, 2.0, 3.0])     # explicit data
A = torch.tensor([[1, 2], [3, 4]])    # ints → int64 by default

In [14]:
# shapes / dtypes
print(x.shape)          # torch.Size([3])
print(x.dtype)          # torch.int64
x[1:]

torch.Size([3])
torch.float32


tensor([2., 3.])

In [28]:
# Dtype & device
y = torch.ones(2, 3, dtype=torch.float32)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
y = y.to(device)                      # move to GPU if available

cpu


In [19]:
# Reshape vs view
t = torch.arange(12)          # shape [12]
print(t)
t2 = t.reshape(3, 4)          # 3×4 (may copy)
print(t2)
t3 = t.view(3, 4)             # 3×4 (shares memory when possible)
print(t3)
t4 = t2.flatten()             # back to [12]
print(t4)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [30]:
# Concatenate & stack
a = torch.ones(2, 3)
print(a)
b = torch.zeros(2, 3)
print(b)
cat = torch.cat([a, b], dim=0)   # shape [4,3] — append rows
print(cat)
stk = torch.stack([a, b], dim=0) # shape [2,2,3] — new axis
print(stk)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [32]:
# Broadcasting (auto-expansion of compatible shapes)
M = torch.ones(3, 4)              # [3,4]
print(M)
v = torch.tensor([1., 2., 3., 4.])# [4]
print(v)
out = M + v                        # v → [3,4] behind the scenes
print(out)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([1., 2., 3., 4.])
tensor([[2., 3., 4., 5.],
        [2., 3., 4., 5.],
        [2., 3., 4., 5.]])


🧩 2️⃣ Random Seed — what’s torch.manual_seed(42)?

Every time you create random numbers, like torch.randn(…), PyTorch uses an internal random number generator.

If you run the same code twice, you’ll normally get different random numbers.

That’s sometimes bad — because you can’t reproduce your experiment.

So we use a seed — a “starting point” for the random generator — to make results repeatable.

In [54]:
torch.manual_seed(2)

In [55]:
r1 = torch.randn(1,11)

In [56]:
print(r1)

tensor([[ 0.3923, -0.2236, -0.3195, -1.2050,  1.0445, -0.6332,  0.5731,  0.5409,
         -0.3919, -1.0427,  1.3186]])


In [49]:
torch.manual_seed(2)
r2 = torch.randn(1, 11)
print(r2)

tensor([[ 0.3923, -0.2236, -0.3195, -1.2050,  1.0445, -0.6332,  0.5731,  0.5409,
         -0.3919, -1.0427,  1.3186]])


## 🧠 Exercise 1 — Add a vector to a matrix (row broadcasting)

In [60]:
a = torch.arange(1, 25)
a = a.reshape(4, 6)

In [63]:
b = torch.ones((6))

In [64]:
print(b)

tensor([1., 1., 1., 1., 1., 1.])


In [65]:
b + a

tensor([[ 2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13.],
        [14., 15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24., 25.]])

## 🧠 Exercise 2 — Add a column vector to a matrix (column broadcasting)

In [68]:
a = torch.arange(1, 25)
a = a.reshape(2, 12)

In [69]:
print(a)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])


In [70]:
b = torch.tensor([[1.], [1.]])

In [71]:
b

tensor([[1.],
        [1.]])

In [72]:
b + a

tensor([[ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
        [14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.]])