## 🧩 Step 1D — Tensor Operations & Manipulations

(this is where you go from “I know tensors exist” → “I can actually work with data like a pro”)

#  🧱 1️⃣ What are “tensor operations”?

A tensor operation is any math, indexing, or transformation you do on a tensor.
Examples:

* arithmetic (+ – * / @)

* shape changes (view, reshape, transpose)

* reductions (sum, mean, max)

* combining (cat, stack)

* logical (>, ==, masking`)

Essentially, every operation is the language PyTorch uses to describe computation graphs.

# 🧮 2️⃣ Arithmetic & element-wise ops

In [1]:
import torch

In [8]:
a = torch.tensor([1,2,3,4])
b = torch.tensor([1,3,3,4])

In [9]:
a, b

(tensor([1, 2, 3, 4]), tensor([1, 3, 3, 4]))

In [10]:
print(a+b)

tensor([2, 5, 6, 8])


In [11]:
print(a-b)

tensor([ 0, -1,  0,  0])


In [12]:
print(a*b)

tensor([ 1,  6,  9, 16])


In [13]:
print(a/b)

tensor([1.0000, 0.6667, 1.0000, 1.0000])


In [14]:
print(a**2)

tensor([ 1,  4,  9, 16])


In [15]:
print(torch.exp(a))

tensor([ 2.7183,  7.3891, 20.0855, 54.5981])


In [16]:
print(torch.log(a))

tensor([0.0000, 0.6931, 1.0986, 1.3863])


# 🔄 3️⃣ Reductions (“collapse along dimensions”)

In [17]:
a = torch.arange(1, 13).float().reshape(3, 4)

In [18]:
print(a)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [19]:
print(a.sum())

tensor(78.)


In [23]:
print(a.mean(dim=0))    # column-wise mean → shape [4]

tensor([5., 6., 7., 8.])


In [24]:
print(a.mean(dim=1))    # row-wise mean → shape [3]

tensor([ 2.5000,  6.5000, 10.5000])


In [25]:
print(a.max())          # global max

tensor(12.)


# 🧩 4️⃣ Indexing & slicing 

same as numpy

# 🔀 5️⃣ Shape operations

Reshaping and transposing are everywhere in ML (especially in attention models).

In [29]:
t = torch.arange(12).reshape(3,4)
# print(t.T)               # transpose → shape [4,3]
# print(t.view(2,6))       # reshape (shares memory)
# print(t.reshape(2,6))    # similar but safer
# print(t.flatten())       # 1-D view
print(t.unsqueeze(0))  # add new axis at front → [1,3,4]
print(t.unsqueeze(2))  # add new axis at end  → [3,4,1]
# print(t.squeeze())     # remove dims of size 1

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])
tensor([[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]]])


# 🔗 6️⃣ Combining tensors

Two main tools: cat (join existing axis) and stack (create new axis).

In [33]:
a = torch.ones(2,3)
b = torch.zeros(2,3)

cat0 = torch.cat([a,b], dim=0)   # shape [4,3]
print(cat0)
cat1 = torch.cat([a,b], dim=1)   # shape [2,6]
print(cat1)
stk  = torch.stack([a,b], dim=0) # shape [2,2,3]
print(stk)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


# 🎯 Mini-Exercises (try each yourself)

## 1️⃣ Create a 3×4 tensor with values 1-12.

### Compute the mean of each column and each row.

In [36]:
a = torch.arange(1, 13).float().reshape(3,4)
print(a)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [38]:
a.mean(dim=0) # column wise means

tensor([5., 6., 7., 8.])

In [39]:
a.mean(dim=1) # row wise means

tensor([ 2.5000,  6.5000, 10.5000])

## 2️⃣ Select the middle two columns using slicing.

In [41]:
a[:, 1:3]

tensor([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.]])

## 3️⃣ Add a new axis at the front (so shape [1,3,4]).

In [44]:
a.unsqueeze(0).shape

torch.Size([1, 3, 4])

## 4️⃣ Flatten the tensor back to 1-D.

In [45]:
a.flatten()

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

## 5️⃣ Concatenate two copies of it along axis 0.

In [47]:
torch.cat([a,a], axis=1)

tensor([[ 1.,  2.,  3.,  4.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.,  9., 10., 11., 12.]])