# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

### 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [2]:
!pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 9.6 MB/s eta 0:00:00:00:0100:01


In [3]:
import numpy as np

In [28]:
a = np.array((1,2,3,4,5,6,7,8,9,10))

In [29]:
a.size

10

In [30]:
a.dtype

dtype('int64')

In [31]:
a.shape

(10,)

In [32]:
a.reshape([2,5])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [45]:
a = np.random.randint(1, 21, size = (5,5))

In [46]:
a

array([[13,  3,  7, 20, 13],
       [18,  3,  3, 10,  3],
       [13, 16, 20,  7,  8],
       [ 1,  7, 19,  9, 16],
       [ 5,  4, 10, 16, 12]])

In [65]:
a[:, 2] = 1

In [66]:
b = np.random.randint(1, 17, size = (4,4))

In [70]:
np.fill_diagonal(b, 0)
b

array([[ 0, 11, 14,  9],
       [ 8,  0, 13,  1],
       [11, 14,  0, 11],
       [11, 14,  9,  0]])

### 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [74]:
a = np.random.randint(1, 37, size = (6,6))
a

array([[24, 15, 26, 35, 18, 20],
       [ 9,  9, 29, 24, 32, 16],
       [23, 27, 10,  7, 14,  7],
       [ 2,  7, 27, 22, 34, 31],
       [13, 22, 36, 30,  9, 23],
       [ 6, 23, 29, 15, 20, 24]])

In [75]:
a[2:6, 1:5]

array([[27, 10,  7, 14],
       [ 7, 27, 22, 34],
       [22, 36, 30,  9],
       [23, 29, 15, 20]])

In [83]:
b = np.random.randint(1, 26, size = (5,5))
print(b)
border_elements = np.concatenate((b[0, :], b[-1, :], b[1:-1, 0], b[1:-1, -1]))
border_elements 

[[10 17 21  9 12]
 [ 3 24 23  6  5]
 [20 19 24  3 18]
 [24  8 22 15 23]
 [20 12 20 10 23]]


array([10, 17, 21,  9, 12, 20, 12, 20, 10, 23,  3, 20, 24,  5, 18, 23])

### 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [91]:
a = np.ones((3,4))
b = np.random.randint(1, 21, size = (3, 4))

In [94]:
b

array([[ 5,  8,  4,  8],
       [ 9,  7,  2, 11],
       [ 2, 11,  1, 20]])

In [95]:
a + b

array([[ 6.,  9.,  5.,  9.],
       [10.,  8.,  3., 12.],
       [ 3., 12.,  2., 21.]])

In [97]:
b - a

array([[ 4.,  7.,  3.,  7.],
       [ 8.,  6.,  1., 10.],
       [ 1., 10.,  0., 19.]])

In [98]:
b * 3

array([[15, 24, 12, 24],
       [27, 21,  6, 33],
       [ 6, 33,  3, 60]])

In [101]:
a = np.random.randint(1, 12, size = (4,4))

In [102]:
a

array([[10,  7, 11,  6],
       [ 9,  8,  8,  3],
       [ 7,  6, 10,  8],
       [ 2,  9,  6,  5]])

In [108]:
colSize = a.shape[0]
rowSize = a.shape[1]

In [112]:
colsum = 0
for i in range(colSize):
    colsum += sum(a[:, i])
print(colsum)

115


### 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [ ]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Compute the statistical values
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

Original array:
[[18 16  3 19 17]
 [11 20 18 17  1]
 [ 5  7 10 12 14]
 [ 8 18 12 17  7]
 [17  6  9 17 20]]
Mean: 12.76
Median: 14.0
Standard Deviation: 5.594854779169876
Variance: 31.3024


In [121]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array:")
print(normalized_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
